name: GOGOGO v1

on:
  schedule:
    - cron: "25 9,18 * * *"
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          config: "config.yml"
          secrets: ${{ secrets.secrets }}