name: GOGOGO

on:
  #schedule:
  #  - cron: "15 7,18 * * *"
  workflow_dispatch:

jobs:
  automation:
    name: 自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@56e02cbf8efdf007a6d446351a031a8cf7408e9e
        with:
          modules:  ${{ secrets.modules || 'report,ad_handler,login,sign,guild,answer,lottery,logout,discord,line_notify' }}
          parameters: ${{ secrets.parameters || '{}' }}
          secrets: ${{ secrets.secrets }}
          browser: '{ "type": "webkit" }'
      - uses: gautamkrishnar/keepalive-workflow@master
