name: 自動化 (Docker)

on:
  schedule:
    - cron: "25 9,18 * * *"
  workflow_dispatch:

jobs:
  automation:
    name: 自動化 (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge Secrets
        run: node merge.js
        env:
          config: config.yml
          secrets: ${{ secrets.SECRETS }}

      - name: Run Automation
        run: docker run --rm -v "$(pwd)/merged-config.yml:/config.yml" -e TZ=Asia/Taipei jacoblincool/bahamut-automation

      - uses: gautamkrishnar/keepalive-workflow@master
